### ISSUE TITLE
Support file-based secrets

### ISSUE THREAD

**Issue by avargaskun** [elmerfds/TrafegoDNS#251]
Hi! Thank you for all the work on this project. It's a really cool idea, looking forward to integrate into our workflows.

I wanted to drop a suggestion. For secret management, would it be possible to use files rather than clear-text in the environment variables?

Currently we use secrets as per: https://docs.docker.com/compose/how-tos/use-secrets/

I imagine it could look something like below (notice the use of `CLOUDFLARE_TOKEN_FILE` instead of `CLOUDFLARE_TOKEN`)

```yaml
secrets:
  cloudflare_dns_api_token:
    file: ./secrets/cloudflare/dns_api_token
services:
  trafego:
    container_name: trafego
    image: eafxx/traefik-dns-manager:latest
    restart: unless-stopped
    networks:
      - ${DOCKER_NETWORK}
    volumes: 
      - ${APPDATA_LOCATION:-/srv/appdata}/trafego:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - cloudflare_dns_api_token
    environment:
      DNS_PROVIDER: cloudflare
      DNS_DEFAULT_MANAGE: false
      CLOUDFLARE_TOKEN_FILE: /run/secrets/cloudflare_dns_api_token
      TRAEFIK_API_URL: http://traefik:8080/api
```
