### ISSUE TITLE
Automatic configuration of Traefik api@internal service is not supported

### ISSUE THREAD

**Issue by avargaskun** [elmerfds/TrafegoDNS#269]
Using the `traefik` integration mode does not seem to support the internal API endpoint in Traefik. Here is my traefik configuration (summarized to only relevant labels)

```yaml
  traefik:
    container_name: traefik
    image: traefik:v3.3
    labels:
      dns.manage: true
      dns.content: ${TAILSCALE_IP}
      traefik.enable: true
      traefik.http.routers.api.entryPoints: tailnet
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.rule: Host(`traefik.example.com`)
```

After investigation, discovered that the reason was that the route-matching logic in TraefikMonitor was not finding a match between the domain in the rule (traefik.example.com) and any of the containers. 

These are the matching conditions in TraefikMonitor (lines 285-287):

```javascript
          containerId.includes(serviceName) || 
          containerLabels[`${this.config.traefikLabelPrefix}http.routers.${routerName}.service`] === serviceName ||
          containerLabels[`${this.config.traefikLabelPrefix}http.services.${serviceName}.loadbalancer.server.port`]
```

For most containers, the first rule is enough to match. However, rule 2 should have matched my configuration. There are 2 reasons it doesn't:

1. Currently, `routerName` is being set to the index of the router in the list of routers returned by Traefik's API, not the actual `name` attribute
2. Traefik adds a suffix to router names, i.e. `@<provider>` so the router name returned by Traefik is `api@docker` but in the container labels, normally the provider suffix is not used because it is implied, i.e. `api`

I did a fix on my local build of Trafego, will share a PR that better illustrates this 😄
